apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      securityContext:
        runAsUser: 1001
        
        runAsGroup: 1001
        fsGroup: 1001
       #readOnlyRootFilesystem: true
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30


      containers:
        - name: auth
          image: mpoyd/kubeguardian-auth-svc:latest@sha256:a3bfde3eb8948275ea5031c63c7c4a33279bb61d598c606c99fa81d5c8b32716
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: HOSTDB
              value: pgpool-svc.database-auth.svc.cluster.local
            - name: PASSDB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgresql-password
          livenessProbe:
            httpGet:
              port: 3001
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 3001
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]

